version: '3.9'
services:
   app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run app"  
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: "development"
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules 
    networks:
      networ_service:
      
   mongo-db:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      networ_service:

networks:
  networ_service:
    driver: bridge